services:
  sqlserver:
    container_name: pkm-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - pkm-sqlserver-data:/var/opt/mssql

  api:
    container_name: pkm-api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=sqlserver,1433;Database=PokemonTrainingCenter;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"
    depends_on:
      - sqlserver

  web:
    container_name: pkm-web
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - api

volumes:
  pkm-sqlserver-data:
