// <auto-generated />
using System;
using CentroTreinamentoPokemon.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CentroTreinamentoPokemon.Infrastructure.Migrations
{
    [DbContext(typeof(CentroTreinamentoPokemonContext))]
    [Migration("20260717010305_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.Matricula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataEncerramento")
                        .HasColumnType("DATETIME2");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("DATETIME2");

                    b.Property<int>("PlanoTreinamentoId")
                        .HasColumnType("INT");

                    b.Property<int>("PokemonId")
                        .HasColumnType("INT");

                    b.Property<int>("Status")
                        .HasColumnType("INT");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanoTreinamentoId");

                    b.HasIndex("PokemonId")
                        .IsUnique()
                        .HasDatabaseName("UX_Matricula_Pokemon_Ativa")
                        .HasFilter("[Status] = 1");

                    b.ToTable("Matricula", null, t =>
                        {
                            t.HasCheckConstraint("CK_Matricula_Status", "[Status] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_Matricula_ValorMensal", "[ValorMensal] > 0");
                        });
                });

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.PlanoTreinamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("VARCHAR(300)");

                    b.Property<int>("NivelPlano")
                        .HasColumnType("INT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("DECIMAL(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("NivelPlano")
                        .IsUnique();

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("PlanoTreinamento", null, t =>
                        {
                            t.HasCheckConstraint("CK_PlanoTreinamento_NivelPlano", "[NivelPlano] BETWEEN 1 AND 3");

                            t.HasCheckConstraint("CK_PlanoTreinamento_ValorMensal", "[ValorMensal] > 0");
                        });
                });

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Nivel")
                        .HasColumnType("INT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("VARCHAR(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("INT");

                    b.Property<int>("TreinadorId")
                        .HasColumnType("INT");

                    b.HasKey("Id");

                    b.HasIndex("TreinadorId");

                    b.ToTable("Pokemon", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pokemon_Nivel", "[Nivel] BETWEEN 1 AND 100");
                        });
                });

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.Treinador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CidadeOrigem")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("VARCHAR(254)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("VARCHAR(150)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Treinador", (string)null);
                });

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.Matricula", b =>
                {
                    b.HasOne("CentroTreinamentoPokemon.Domain.Entities.PlanoTreinamento", "PlanoTreinamento")
                        .WithMany("Matriculas")
                        .HasForeignKey("PlanoTreinamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CentroTreinamentoPokemon.Domain.Entities.Pokemon", "Pokemon")
                        .WithMany("Matriculas")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlanoTreinamento");

                    b.Navigation("Pokemon");
                });

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.Pokemon", b =>
                {
                    b.HasOne("CentroTreinamentoPokemon.Domain.Entities.Treinador", "Treinador")
                        .WithMany("Pokemons")
                        .HasForeignKey("TreinadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Treinador");
                });

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.PlanoTreinamento", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.Pokemon", b =>
                {
                    b.Navigation("Matriculas");
                });

            modelBuilder.Entity("CentroTreinamentoPokemon.Domain.Entities.Treinador", b =>
                {
                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
